### PR TITLE
Get it working on ansible 2.7

### PR DESCRIPTION
**Pull request by spicysomtam**
Hope you are receptive to others working on this. It now works for ansible 2.7 state:present state:absent. Any suggestions for improvement welcome.

### CODE REVIEW

**Comment by mmochan** [comment]
@spicysomtam Apologies for the very late reply. 
Thank you for fixing this up, I must admit I haven't touched this in a very long time. If you want to take it over and submit to ansible then you are most welcome.

**Comment by psharkey** [comment]
@mmochan Would it be ok if I submitted this to ansible and referenced this PR?

**Comment by spicysomtam** [comment]
I had a quick look at the requirements for submitting it. Needs some testing to ensure compatibility. I don't have time to do that and also python is not my top skill (I am more of a linux admin/devops engineer). It was interesting getting this module working and doing a bit more python. If someone else wishes to polish it and get it submitted, its ok by me :) I would say just fork it and work on it if it interests you?

**Comment by mmochan** [comment]
@spicysomtam I have submitted and had accepted a number of modules into Ansible over the years but the process to do so now has become more frustrating. I originally wrote this module as a quick fix and I had no intention of submitting it. Thanks again for your update.

**Comment by mmochan** [comment]
@psharkey You are most welcome to take this code and submit it to Ansible, but you would need to read the docs about how this is done. Referencing this PR is not an option. You would need fork Ansible and follow the process.

**Comment by psharkey** [comment]
@mmochan @spicysomtam I'll get the ansible sanity test (bin/ansible-test sanity --test pep8 --include modules/cloud/amazon/ec2_asg_scheduled_action.py) passing and then open a PR against ansible.

**Pull request merged**
